#!/bin/bash

if !(cargo clippy --version); then
    printf 'Checks requires clippy; try `rustup component add clippy-preview`.\n'
    printf "If that doesn't fix things; try `rustup self update`.\n"
    exit 1
fi

if !(cargo fmt --version); then
    printf 'Checks requires rustfmt; try `rustup component add rustfmt-preview`.\n'
    printf "If that doesn't fix things; try `rustup self update`.\n"
    exit 1
fi

printf 'Running rustfmt:\n'

if ! (cargo fmt --all -- --check); then
    printf '\nRustfmt failed. Please run rustfmt.\n'
    exit $?
fi

printf 'Rustfmt check passed.\n'

printf 'Running clippy:\n'

if ! (cargo clippy --all -- -D warnings); then
    printf '\nClippy has nits. :(\n'
    exit $?
fi

printf 'Clippy check passed.\n'


printf 'Checking compiler warnings:\n'

if ! (RUSTFLAGS="-D warnings" cargo check --all); then
    printf '\nCargo check produced errors. Exiting.\n'
    exit $?
fi

printf 'Check passed!\n'

printf 'Running "cargo test --all"\n'

if ! (cargo test --all); then
    exit $?
fi

printf 'Tests passed!\n'
printf 'Benchmarks are disabled in xi-editor-ph7; skipping cargo bench.\n'
printf 'Workspace limited to core crates (xi-core, xi-core-lib, xi-plugin-lib, xi-rope, xi-rpc, xi-trace, xi-unicode).\n'

printf 'All checks passed.\n'
